# Generated by Django 4.2.10 on 2024-02-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('app_name', models.CharField(blank=True, max_length=64, null=True)),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('end_time', models.BigIntegerField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'log_app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogDns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('client_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('rdata', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_dns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogNetflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('ip_src', models.CharField(blank=True, max_length=15, null=True)),
                ('ip_dst', models.CharField(blank=True, max_length=15, null=True)),
                ('port_src', models.IntegerField(blank=True, null=True)),
                ('port_dst', models.IntegerField(blank=True, null=True)),
                ('time_start', models.BigIntegerField(blank=True, null=True)),
                ('time_end', models.BigIntegerField(blank=True, null=True)),
                ('len', models.IntegerField(blank=True, null=True)),
                ('pkt_list', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'log_netflow',
                'managed': False,
            },
        ),
    ]
